const testItem = {
  _id: 0,
  relatedItems: [
    {
      _id: 10,
      tags: ['Dogs', 'Cats', 'Pigs'],
      price: 10.99,
      imageUrl: 'http://placeimg.com/640/480/transport',
      description: 'Dogs, cats, pigs',
      details: ['Handmade', 'Hipster Approved'],
      seller: 'Test shop',
      shippingStatus: 'Free shipping eligible',
      favorite: false,
    },
    {
      _id: 12,
      tags: ['Dogs', 'Cats', 'Pigs', 'Cows'],
      price: 10.99,
      imageUrl: 'http://placeimg.com/640/480/abstract',
      description: 'Dogs, cats, pigs, cows',
      details: ['Handmade', 'Hipster Approved'],
      seller: 'Fake Fake',
      shippingStatus: 'Free shipping eligible',
      favorite: false,
    },
    {
      _id: 15,
      tags: ['Dogs', 'Cats'],
      price: 1.99,
      imageUrl: 'http://placeimg.com/640/480/people',
      description: 'Dogs, cats',
      details: ['Handmade', 'Hipster Approved'],
      seller: 'Dogs Shop',
      shippingStatus: 'Free shipping eligible',
      favorite: false,
    },
    {
      _id: 18,
      tags: ['Cats', 'Cats', 'Cats', 'Cats'],
      price: 14.25,
      imageUrl: 'http://placeimg.com/640/480/food',
      description: 'Cats, cats, Cats, Cats',
      details: ['Handmade', 'Hipster Approved', 'Cat Approved'],
      seller: 'Cat Lady',
      shippingStatus: 'Free shipping eligible',
      favorite: false,
    },

  ],
  shopItems: [
    {
      _id: 71,
      tags: ['Dogs', 'Cats', 'Pigs'],
      price: 10.99,
      imageUrl: 'http://placeimg.com/640/480/transport',
      description: 'Dogs, cats, pigs',
      details: ['Handmade', 'Hipster Approved'],
      seller: 'Nenas Shop',
      shippingStatus: 'Free shipping eligible',
      favorite: false,
    },
    {
      _id: 72,
      tags: ['Dogs', 'Cats', 'Pigs', 'Cows'],
      price: 10.99,
      imageUrl: 'http://placeimg.com/640/480/abstract',
      description: 'Dogs, cats, pigs, cows',
      details: ['Handmade', 'Hipster Approved'],
      seller: 'Nenas Shop',
      shippingStatus: 'Free shipping eligible',
      favorite: false,
    },
    {
      _id: 73,
      tags: ['Dogs', 'Cats'],
      price: 1.99,
      imageUrl: 'http://placeimg.com/640/480/people',
      description: 'Dogs, cats',
      details: ['Handmade', 'Hipster Approved'],
      seller: 'Nenas Shop',
      shippingStatus: 'Free shipping eligible',
      favorite: false,
    },
    {
      _id: 74,
      tags: ['Cats', 'Cats', 'Cats', 'Cats'],
      price: 14.25,
      imageUrl: 'http://placeimg.com/640/480/food',
      description: 'Cats, cats, Cats, Cats',
      details: ['Handmade', 'Hipster Approved', 'Cat Approved'],
      seller: 'Nenas Shop',
      shippingStatus: 'Free shipping eligible',
      favorite: false,
    },
  ],
};

export default testItem;
