const testItem = {
  _id: 0,
  relatedItems: [
    {
      _id: 10,
      name: 'test text here',
      price: 10.99,
      imageUrl: ['http://placeimg.com/640/480/transport', 'http://placeimg.com/640/480/transport', 'http://placeimg.com/640/480/transport'],
      description: 'Dogs, cats, pigs',
      details: ['Handmade', 'Hipster Approved'],
      seller: 'Test shop',
      shippingStatus: 'Free shipping eligible',
    },
    {
      _id: 12,
      name: 'test text here',
      price: 10.99,
      imageUrl: ['http://placeimg.com/640/480/transport', 'http://placeimg.com/640/480/transport', 'http://placeimg.com/640/480/transport'],
      description: 'Dogs, cats, pigs, cows',
      details: ['Handmade', 'Hipster Approved'],
      seller: 'Fake Fake',
      shippingStatus: 'Free shipping eligible',
    },
    {
      _id: 15,
      name: 'test text here',
      price: 1.99,
      imageUrl: ['http://placeimg.com/640/480/transport', 'http://placeimg.com/640/480/transport', 'http://placeimg.com/640/480/transport'],
      description: 'Dogs, cats',
      details: ['Handmade', 'Hipster Approved'],
      seller: 'Dogs Shop',
      shippingStatus: 'Free shipping eligible',
    },
    {
      _id: 18,
      name: 'test text here',
      price: 14.25,
      imageUrl: ['http://placeimg.com/640/480/transport', 'http://placeimg.com/640/480/transport', 'http://placeimg.com/640/480/transport'],
      description: 'Cats, cats, Cats, Cats',
      details: ['Handmade', 'Hipster Approved', 'Cat Approved'],
      seller: 'Cat Lady',
      shippingStatus: 'Free shipping eligible',
    },

  ],
  shopItems: [
    {
      _id: 71,
      name: 'test text here',
      price: 10.99,
      imageUrl: ['http://placeimg.com/640/480/transport', 'http://placeimg.com/640/480/transport', 'http://placeimg.com/640/480/transport'],
      description: 'Dogs, cats, pigs',
      details: ['Handmade', 'Hipster Approved'],
      seller: 'Nenas Shop',
      shippingStatus: 'Free shipping eligible',
    },
    {
      _id: 72,
      name: 'test text here',
      price: 10.99,
      imageUrl: ['http://placeimg.com/640/480/transport', 'http://placeimg.com/640/480/transport', 'http://placeimg.com/640/480/transport'],
      description: 'Dogs, cats, pigs, cows',
      details: ['Handmade', 'Hipster Approved'],
      seller: 'Nenas Shop',
      shippingStatus: 'Free shipping eligible',
    },
    {
      _id: 73,
      name: 'test text here',
      price: 1.99,
      imageUrl: ['http://placeimg.com/640/480/transport', 'http://placeimg.com/640/480/transport', 'http://placeimg.com/640/480/transport'],
      description: 'Dogs, cats',
      details: ['Handmade', 'Hipster Approved'],
      seller: 'Nenas Shop',
      shippingStatus: 'Free shipping eligible',
    },
    {
      _id: 74,
      name: 'test text here',
      price: 14.25,
      imageUrl: ['http://placeimg.com/640/480/transport', 'http://placeimg.com/640/480/transport', 'http://placeimg.com/640/480/transport'],
      description: 'Cats, cats, Cats, Cats',
      details: ['Handmade', 'Hipster Approved', 'Cat Approved'],
      seller: 'Nenas Shop',
      shippingStatus: 'Free shipping eligible',
    },
  ],
};

export default testItem;
